services:
  - type: web
    name: sunbeltsupply
    runtime: python3.13.1
    buildCommand: pip install -r requirements.txt
    startCommand: cd SunbeltSupply && gunicorn --worker-class aiohttp.worker.GunicornWebWorker SunBeltSupply:app
 